name: App-de-investimentos CI
env:
  NODE_ENV: test
  JWT_SECRET: segredo
on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Instala o node com a versão 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Roda o MySql através do Docker
        run: docker login -u bernardo18 -p ${{ secrets.SECRET_TOKEN }}
        run: docker-compose up -d

      - name: Instala as dependências
        run: npm install

      - name: Realiza os testes
        run: npm test
